### ISSUE TITLE
not worls

### ISSUE THREAD

**Issue by mixserrm999** [MiDo-kun/Mugi-Bot#1]
for me

**Comment by MiDo-kun** [comment]
in what way??

**Comment by MiDo-kun** [comment]
i update the quick installation guide you can use it as reference.

**Comment by mixserrm999** [comment]
Bot is starting.
ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
Server is offline.

**Comment by mixserrm999** [comment]
like it

**Comment by mixserrm999** [comment]
Where did it go wrong????

**Comment by MiDo-kun** [comment]
Wait it does work on my part, can you try it again? It should be something like this.

![Screenshot_2023_0617_071704](https://github.com/MiDo-kun/Mugi-Bot/assets/72369026/3f60fd7f-c862-4501-8400-a76108db1245)

**Comment by mixserrm999** [comment]
bro iknos what happend , i try using my fbstate it work

**Comment by MiDo-kun** [comment]
okay that's good
